services:
  mongo:
    image: mongo:6.0
    container_name: mongo-alertms
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  alert-ms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin123
      MONGO_AUTH_DB: admin
      MONGO_DB: alertdb

volumes:
  mongo-data:
