server:
  port: 8080

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:mongo}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin123}
      authentication-database: ${MONGO_AUTH_DB:admin}
      database: ${MONGO_DB:alertdb}
